import { CharSetConfig, DduSetSymbol } from "../types";

const dduCharSet: CharSetConfig = {
  symbol: DduSetSymbol.DDU,
  charSet: ["뜌", "땨", "이", "우", "야", "!", "?", "."],
  maxRequiredLength: 8,
  bitLength: 3, // 8 = 2^3
  paddingChar: "뭐",
};

const oneCharSet: CharSetConfig = {
  symbol: DduSetSymbol.ONECHARSET,
  charSet: [
    "A",
    "s",
    "q",
    "r",
    "0",
    "z",
    "3",
    "t",
    "y",
    "1",
    "5",
    "2",
    "4",
    "E",
    "B",
    "C",
    "Q",
    "F",
    "R",
    "T",
    "U",
    "W",
    "V",
    "X",
    "Y",
    "Z",
    "b",
    "a",
    "c",
    "d",
    "D",
    "G",
    "L",
    "H",
    "I",
    "-",
    "J",
    "K",
    "M",
    "O",
    "N",
    "f",
    "e",
    "h",
    "g",
    "P",
    "i",
    "S",
    "k",
    "l",
    "m",
    "u",
    "j",
    "v",
    "n",
    "o",
    "p",
    "9",
    "w",
    "6",
    "7",
    "8",
    "x",
    "_",
  ],
  paddingChar: "=",
  maxRequiredLength: 64,
  bitLength: 6, // 64 = 2^6
};

const twoCharSet: CharSetConfig = {
  symbol: DduSetSymbol.TWOCHARSET,
  charSet: [
    'Ok',   '-d',   'b4',   'mF',   'pP',   'vL',   'eA',   '87',
    '2j',   'G8',   'Bj',   'PR',   'eI',   'a6',   'pQ',   'eZ',
    'qv',   '3j',   'h6',   '-2',   '1I',   'tc',   'qa',   'OX',
    '5z',   'vn',   'p1',   'OL',   'XC',   'N8',   'qW',   'hH',
    '-C',   '_o',   'BQ',   '54',   'O7',   'BT',   '-7',   '8c',
    'gs',   'MC',   'kz',   'hx',   'Jt',   'ZL',   'Po',   'ZI',
    'VU',   'M2',   'sg',   'Xr',   'YR',   'T4',   'J0',   'J4',
    'KW',   'ho',   'hI',   'Bw',   'd9',   'iU',   'eC',   'Sm',
    'V4',   'fd',   'mz',   'Ac',   'KT',   'Gw',   '3r',   'K2',
    'pi',   '_Y',   'ax',   'Ho',   'OQ',   'J7',   'b8',   'OA',
    'Oz',   'bv',   'pA',   'pt',   'ZU',   'mU',   'A6',   'kc',
    'KV',   'hA',   'vR',   'B6',   'fY',   'wz',   'i7',   'Ou',
    'ic',   '_U',   '-F',   'TL',   'WL',   'T6',   '14',   '_9',
    'Kj',   'Nj',   'HU',   '-1',   '3m',   '5L',   'tR',   'wj',
    '0L',   'DH',   'hn',   'ed',   'S8',   'q1',   'Di',   '8r',
    'kR',   'Nt',   'iz',   'uI',   '-6',   'Ma',   'k6',   'Yx',
    'qR',   'e1',   'ft',   'OI',   '3a',   'SR',   'bR',   'G9',
    'Pj',   'eu',   '5F',   'ur',   'h9',   'q9',   'M6',   '2r',
    'fL',   'i9',   'ij',   'Yz',   'S5',   'Hn',   'eW',   'DU',
    '0o',   'Ar',   'MH',   'BY',   'GU',   'bd',   '_R',   'dx',
    '-I',   'kQ',   'ei',   'M8',   'ir',   'pZ',   '8U',   'Dn',
    'e2',   'Az',   'D7',   '09',   'fv',   'vF',   'f7',   'JW',
    'hc',   'tC',   'P6',   '1U',   'D2',   'to',   'H9',   'pX',
    'Nm',   'Kd',   'e9',   '_2',   'dI',   '3n',   'vQ',   '_7',
    'MU',   'MA',   'Mj',   'Zr',   'K0',   'eF',   'SV',   'Hj',
    'ar',   'NW',   'wC',   'Vr',   'H4',   '35',   '5x',   'NF',
    'u9',   '3W',   'S6',   'Nr',   'eU',   'px',   'O5',   '-V',
    'NC',   'GQ',   'K6',   'Nd',   'KZ',   'bc',   '3F',   'N6',
    'dn',   'wF',   'dC',   'Jw',   '34',   '04',   '1Q',   'v6',
    'JX',   'bI',   'm9',   '38',   'Z7',   'Gc',   'N4',   'pu',
    'Su',   'hj',   '2x',   'kF',   'B5',   'Mc',   'BU',   'qC',
    '3o',   '-U',   'Gv',   'Gu',   'Gj',   'ex',   'in',   'wL',
    'OU',   'w6',   'Kk',   'ko',   'Sx',   'h0',   'BL',   'DT',
    'tQ',   'Aj',   'Xj',   'p4',   'fI',   'Xo',   'Xx',   'Z4',
    'P4',   'MV',   '0U',   'bt',   'hY',   '2F',   'qF',   'TR',
    'ew',   '5U',   'h8',   '1F',   'DZ',   'v9',   'GT',   'OC',
    'Px',   'B0',   '-w',   '3V',   'vz',   'e0',   'qY',   'Ao',
    'ek',   'JL',   'NU',   'uc',   'OY',   'Jm',   'po',   'Xz',
    '3I',   'Bd',   'mo',   'pr',   'bA',   'uF',   'hV',   '1L',
    'Du',   'KY',   'BF',   '1r',   '8j',   '_I',   'AI',   'uL',
    '_T',   'u7',   '0j',   '-T',   'Jn',   'SU',   'A7',   'pT',
    'PF',   'vI',   'HF',   'Jc',   'JC',   '_x',   '3P',   'T9',
    't6',   'Zz',   'GH',   'hW',   'q8',   'a7',   'ha',   'Nn',
    'qd',   '2c',   'qj',   't9',   'e8',   'TU',   'bj',   'Sw',
    'O2',   'YL',   'MZ',   'hm',   '31',   'b6',   'KL',   '_v',
    'Mw',   'Bc',   'T7',   'DC',   'G4',   'BZ',   'Mt',   '2n',
    'J2',   'fu',   'AU',   'Tr',   'tz',   'Dr',   'SX',   '_j',
    'qV',   '_d',   'h5',   '_V',   'tU',   'iF',   'uj',   'Bn',
    'fn',   'pm',   'bw',   'XF',   'Hz',   '3H',   'YQ',   'pV',
    'pU',   '-u',   '5j',   'wQ',   'fP',   '5r',   '-0',   'PC',
    'K8',   'bu',   'SL',   'm6',   'e7',   'hP',   'Wn',   'O9',
    'uU',   '-Q',   'w9',   'NH',   '1R',   'Oc',   '3C',   'u4',
    'bo',   'bZ',   'Kv',   'GZ',   'Ka',   'pI',   'BA',   'KR',
    't4',   'Mu',   'vC',   'hv',   '-k',   'pL',   'vU',   '8Q',
    'd7',   'ux',   'tF',   '0I',   'e5',   'W7',   'ST',   'bU',
    'Ju',   'Bv',   'pw',   'et',   'B2',   'O0',   'qA',   '3L',
    'SI',   'O8',   'Oa',   'qm',   'Gk',   'aI',   '3d',   'G7',
    'dz',   'uC',   'aj',   'Jj',   '_6',   'Xn',   'VI',   'fz',
    'SQ',   'P9',   'p9',   'em',   '8I',   'Wj',   'dr',   'p7',
    'q5',   'hd',   'qt',   '36',   'io',   'vr',   'GY',   '-5',
    'TC',   'hT',   '24',   'pn',   'i6',   'SW',   'ZR',   'JA',
    'J5',   'MT',   'fC',   'JH',   'YU',   'Bk',   'ev',   'H6',
    'GV',   '8x',   'bH',   '2Q',   'TF',   'Kx',   'vc',   'Gn',
    'Ko',   'aU',   '_5',   'TI',   'Jr',   'Od',   '1c',   '_L',
    'A9',   'K7',   '0R',   'fA',   'DF',   'Ba',   'd4',   'SF',
    'Da',   '-i',   '16',   'hR',   'KF',   'b7',   '3x',   'Nv',
    'KI',   'vj',   'Zc',   'fU',   'eR',   'tL',   'Ga',   'Vz',
    'p6',   'Dj',   'GP',   'qi',   'Tc',   '57',   'fV',   'h7',
    'M7',   'BP',   'eH',   '3X',   'fT',   'Y9',   '30',   'XQ',
    'hi',   '39',   'Ja',   'NQ',   'AC',   'qk',   '_i',   'qL',
    'Gi',   '-A',   'MP',   'qQ',   '0r',   'TQ',   'hZ',   'Jo',
    '2z',   'J9',   'ZC',   'aF',   'Dm',   'Gr',   'Yj',   '_r',
    'AF',   'Mv',   'AR',   'JQ',   'er',   'Gz',   'An',   'p5',
    'hr',   'Bz',   'Zx',   'Jd',   'G6',   'pH',   'bi',   'SH',
    '29',   'bn',   'fQ',   'PU',   'SA',   '59',   'St',   '_X',
    'M1',   'pz',   'fr',   'Mk',   'OH',   'bQ',   'YF',   'bx',
    '_1',   'bT',   'mc',   'h2',   'eo',   '_C',   'D5',   'Bm',
    'KP',   'ea',   'en',   '84',   'DY',   'Ax',   'Mm',   '3R',
    'K9',   'PQ',   'N5',   'f4',   'OV',   'pj',   '1C',   'GR',
    'wc',   'bY',   'VC',   'Si',   'Zn',   'OW',   'DI',   '-j',
    'N0',   'mQ',   'Or',   'q4',   'O1',   'S1',   'eY',   'Ki',
    'DP',   'aC',   'NY',   'iC',   'pR',   'S4',   'KA',   'BV',
    '0c',   'SZ',   'Mr',   'NA',   '3T',   'f1',   'uz',   'XU',
    '-P',   'B4',   'ht',   'VL',   'Yc',   'WQ',   'ac',   'eT',
    'Vo',   'wI',   'iQ',   '_8',   '8C',   'hX',   'WF',   'WC',
    'N7',   'qT',   'N2',   'Bi',   'bm',   '-r',   'D8',   'dU',
    'G0',   'dc',   '2L',   'p2',   'O4',   'v4',   'vx',   'eX',
    'fo',   'ao',   'Wr',   'W4',   'V9',   'Sz',   'XL',   'eV',
    'ba',   '5c',   'SC',   'f6',   '-m',   'aQ',   '5o',   'Pr',
    'fR',   'Sk',   'fi',   'qU',   'JP',   'Jk',   'Na',   'qw',
    'Ox',   'qo',   'W9',   '5C',   'b0',   'N1',   '-v',   '-R',
    'N9',   'wU',   'wo',   'an',   'tx',   'Kr',   'b5',   'Tx',
    'q6',   'q2',   'J1',   'Gt',   '2C',   'BX',   '_a',   'SP',
    'JY',   'Br',   'KH',   'MF',   'AQ',   't7',   'OF',   'Mz',
    'B9',   'HI',   'hk',   'VQ',   'S2',   'f5',   '-n',   'Xc',
    'i4',   'Kt',   '0Q',   'D0',   'Oj',   'PI',   'BH',   'Kc',
    'dj',   'DR',   '3u',   'qz',   'OT',   'Nw',   'Sd',   'K4',
    '1o',   '2R',   'qP',   'bV',   'NV',   'Zj',   'kL',   'k7',
    '_c',   'Bt',   'mR',   'mC',   'kU',   'HR',   'J8',   'Gm',
    'B7',   'e6',   '1z',   '3Q',   'NZ',   'Bu',   '0x',   'Dt',
    'WR',   'BW',   'ZF',   'ix',   'q7',   '1j',   'XI',   'DA',
    'VR',   '56',   'V7',   'iL',   '5n',   'Md',   'vo',   'pa',
    'Y4',   'YI',   '8R',   'Dk',   'pk',   'fk',   'fc',   '_t',
    'Z6',   '-4',   'Y6',   '_Q',   '3t',   '0n',   'f9',   'az',
    'fm',   'hu',   'Z9',   '_4',   '-c',   'f2',   '5Q',   'DW',
    'D9',   'JI',   'JF',   '5I',   'No',   '17',   'AL',   'Nk',
    'Ji',   'Ow',   'iI',   'Mx',   'mr',   '_m',   'f8',   'mL',
    'D1',   '_z',   'Dd',   'WU',   'HC',   '-Z',   'K1',   'Zo',
    'NR',   'GX',   'D6',   'So',   'V6',   'd6',   'fX',   'qH',
    'Ot',   'MI',   '3w',   'iR',   'HL',   'ec',   'JU',   'm7',
    'wr',   'PL',   'G5',   'S0',   '-x',   'NX',   'kj',   'W6',
    '-8',   'ZQ',   'hU',   'GL',   'kC',   '26',   'fx',   '-X',
    'JV',   'B1',   'fH',   'eP',   'OZ',   'pW',   'OP',   '_u',
    'JT',   '2o',   '3Y',   'NI',   'Sn',   'Sr',   'b9',   'SY',
    'DQ',   'm4',   '1n',   'BI',   'hL',   'M0',   'Oo',   '3k',
    'ez',   '3A',   'wR',   'bW',   'K5',   'kr',   'NL',   'a9',
    '-Y',   'bk',   'Dz',   'qX',   'KQ',   'b2',   'Yo',   'hw',
    '3v',   'k9',   'v7',   '5R',   'do',   'GW',   'fW',   '19',
    '_n',   'Sa',   'p8',   'S9',   'MY',   '-a',   'qI',   '8o',
    'dQ',   'h4',   'Nc',   'Dx',   'qZ',   'Gd',   '3Z',   'pc',
    'Sc',   '3U',   'e4',   'Do',   'XR',   'MQ',   'Wz',   '-o',
    'a4',   'KX',   'A4',   'pv',   'On',   '86',   'kn',   'OR',
    'tr',   'Y7',   'YC',   'Om',   'Mi',   'Jx',   'Nu',   'u6',
    '8F',   'fF',   'Jz',   'fa',   'bP',   '-9',   'Ku',   '0F',
    '_F',   'f0',   'M5',   'Hr',   '3z',   'VF',   'w7',   'pY',
    'Dc',   'kI',   'Vj',   '-t',   'ML',   'wx',   '0z',   'Nz',
    'D4',   '3c',   'bX',   '0C',   'Tz',   'Bx',   'HQ',   'pd',
    '2I',   'w4',   '8n',   'hz',   'Yr',   '3i',   'hC',   'dL'
  ],
  paddingChar: "ly",
  maxRequiredLength: 1024,
  bitLength: 10, // 1024 = 2^10
};

// Map을 사용한 효율적인 CharSet 저장소 (O(1) 조회)
const charSetMap = new Map<DduSetSymbol, CharSetConfig>([
  [dduCharSet.symbol, dduCharSet],
  [oneCharSet.symbol, oneCharSet],
  [twoCharSet.symbol, twoCharSet],
]);

export function getCharSet(symbol: DduSetSymbol): CharSetConfig | undefined {
  return charSetMap.get(symbol);
}

export function getAllSymbols(): DduSetSymbol[] {
  return Array.from(charSetMap.keys());
}

export function hasCharSet(symbol: DduSetSymbol): boolean {
  return charSetMap.has(symbol);
}